- name: Install Nginx and deploy
  hosts: webhost
  become: yes
  become_user: root

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure document root exists
      file:
        path: /var/www/html
        state: directory

    - name: Copy website files
      copy:
        src: ./
        dest: /var/www/html
       
